# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Ronak Tripathi's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Ronak Tripathi
headline: and this is a collection of my projects and cool assignments I have undertaken over my career and academic journey
description: As a civil systems engineer I try and use data analysis and systems thinking to develop resilient, agile solutions to the challenges facing our construction industry. I am currently enrolled at the Technische Universit√§t Berlin, in the Masters program Civil Systems Engineering, where we learn to deploy holistic Systems Thinking approach and data analytics to upgrade and digitize construction practices. I currently live in Berlin, where I was employed at the Reib_CFK Projectat Entwerfen und Konstruieren Massivbau and currently I work for the cabon capture mineralization project Seq Kalz at Bauchemie.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/IMG_20251107_144249675_PORTRAIT.jpg


# Link your resume
# You can place your resume in assets/resume/{resume.pdf or add external link such as pdf saved in google drive 
resume-url: /assets/resume/Resume_english.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: ronak-tripathi-9376a913b
  github: ronakTripathi-44
  stackoverflow:   # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: BIM
    tools:
    - Revit
    - AutoCAD
    - Navisworks
    - Fusion 360 (Autodesk)
    - Parametric modelling in Dynamo
    - IFC and OpenBIM principles as outlined in DIN ISO 19650
  - category: Project Mangement
    tools:
    - Power BI
    - Primavera
    - Microsoft Suite
  - category: Structural analysis
    tools:
    - StaadPro
    - Sofistik
    - ABAQUS
    - Karamba
  - category: Programming
    tools:
    - Python
    - MATLAB
    - Rstudio
  - category: Problem Solving / Risk Management
    tools:
    - Root Cause Analysis (e.g., 5 Whys, Fishbone Diagram)
    - DFMEA / PFMEA 
    - Stakeholder analysis
    - AHP Matrix
    - Monte Carlo simulations
    - Sensitivity analyses
    - Agent based modelling
  - category: Rendering
    - Blender
    - Twin motion

# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key: xqeezdew



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
